### DISCUSSION TITLE
Error: Ports are not available, bind: address already in use

### DISCUSSION THREAD

**Discussion by yash-puligundla** [ga4gh/ismb-2022-ga4gh-tutorial#47] [Q&A]
**Error: Ports are not available, bind: address already in use** occurs while running `docker-compose up -d`

**Comment by yash-puligundla** [comment]
This error occurs when you try to run a docker container on a port that is already in use.

**Solution 1:** Kill the process that is currently running on the port and re-try

* Check which process is using the port `sudo lsof -i :<port_number>`
* If this process is not vital, to kill it, use the following command
`kill -9 <PID>` 

**Solution 2:** Change the host port number to a different one
Example docker-compose.yml
```
version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "<**new_host_port_number**>:<docker_container_port>"
```
