### ISSUE TITLE
Notes/Feedback from Dry Part - sessions 2, 3

### ISSUE THREAD

**Issue by yash-puligundla** [ga4gh/ismb-2022-ga4gh-tutorial#40]
Hi @ianfore, I am adding all the items that came up during the dry run. Feel free to ignore anything that doesn't make sense.

- [x] **2-2** Pass SB_API_KEY param to  sbcgcWESClient method
- [x] **2-2** “Edit  the path..” cell should be of type markdown and not code
- [x] Stress that the participants should request for Pilot funds a few days before the tutorial. If they don't have funds, they can use the main project as a workaround.
- [x] **2-2** Correct this line of code:  results_drs_uri = runLog[‘outputs’]**[‘out_alignments’]**[‘path’]
- [x] **2-2** Correct alignment_count typo - it's in the app (make a copy of the app and correct there)
- [x] **3-1** Move backup and completed files to a different directory to avoid any confusion
- [x] consider renaming directories from sessionX to something descriptive
- [x] **2-3** docker-compose takes a minute or 2 to run. If you get an error, wait & re-run.
- [x] Consider adding step numbers on Jupyter notebook cells
- [x] Maybe ask the participants to download docker images used in session 2-3 before hand to save time
- [x] **2-3** docker-compose - use depends on constraint.
**Example:** 
```
dev-data-connect:
    depends_on:
       - trino-db
       - dnastack-data-connect-db
    image: ianfore/data-connect-trino:dev
    container_name: session_2_dev-data-connect
    ports:
      - "8089:8089"
    volumes:
        - ./data-connect-schemas:/models
    environment:
      - TRINO_DATASOURCE_URL=http://host.docker.internal:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:15432/dataconnecttrino
      - SPRING_PROFILES_ACTIVE=no-auth
```
